import maps_between_classifying_spaces_algebraic_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace maps_between_classifying_spaces_algebraic_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end maps_between_classifying_spaces_algebraic_lemma_canonical_lane_mathlib
end HautevilleHouse
